version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 20
  labels:
  - M5-dependencies
  ignore:
  - dependency-name: fp-ts
    versions:
    - ">= 2.0.a, < 2.1"
  - dependency-name: "@polkadot/api"
    versions:
    - "> 0.100.0.pre.beta.28, < 0.101"
  - dependency-name: react-dropzone
    versions:
    - "> 10.1.3, < 10.2"
  - dependency-name: "@storybook/addon-actions"
    versions:
    - ">= 5.0.3.a, < 5.0.4"
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - ">= 5.0.3.a, < 5.0.4"
  - dependency-name: "@storybook/addon-links"
    versions:
    - ">= 5.0.3.a, < 5.0.4"
  - dependency-name: "@storybook/react"
    versions:
    - ">= 5.0.3.a, < 5.0.4"
  - dependency-name: "@polkadot/extension-inject"
    versions:
    - 0.36.1
    - 0.37.1
  - dependency-name: "@types/chrome"
    versions:
    - 0.0.128
    - 0.0.129
    - 0.0.132
    - 0.0.133
    - 0.0.134
  - dependency-name: "@polkadot/dev"
    versions:
    - 0.61.24
    - 0.61.25
    - 0.61.26
    - 0.61.30
    - 0.62.5
    - 0.62.6
    - 0.62.7
  - dependency-name: "@polkadot/extension-dapp"
    versions:
    - 0.36.1
  - dependency-name: "@polkadot/ui-assets"
    versions:
    - 0.65.1
    - 0.69.1
    - 0.70.1
    - 0.71.2
    - 0.71.3
    - 0.72.1
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
    - 5.1.8
  - dependency-name: "@storybook/addon-knobs"
    versions:
    - 6.1.11
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@craco/craco"
    versions:
    - 6.0.0
    - 6.1.0
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
  - dependency-name: react-scripts
    versions:
    - 4.0.1
  - dependency-name: react-dropzone
    versions:
    - 11.2.4
    - 11.3.0
    - 11.3.1
  - dependency-name: styled-components
    versions:
    - 5.2.1
  - dependency-name: electron-builder
    versions:
    - 22.9.1
  - dependency-name: "@storybook/addon-actions"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: "@storybook/addon-links"
    versions:
    - 6.1.15
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.2
    - 6.2.7
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: webpack
    versions:
    - 5.17.0
    - 5.19.0
    - 5.21.2
    - 5.23.0
  - dependency-name: "@polkadot/api"
    versions:
    - 3.6.3
    - 3.6.4
    - 3.8.1
  - dependency-name: "@polkadot/extension-chains"
    versions:
    - 0.36.1
  rebase-strategy: disabled
