language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.0
  - export PATH=$HOME/.yarn/bin:$PATH
install:
  - yarn install
script:
  - yarn build
  - yarn lint
  - yarn test
after_success:
  - yarn fetch-substrate
before_deploy:
  - yarn run storybook-build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  keep_history: true
  local_dir: packages/ui-components/.out
  on:
    branch: master

