name: pr

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: ./scripts/prestart.sh
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn test

  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn package:extension
      - uses: actions/upload-artifact@v1
        env:
          SHA7: ${GITHUB_SHA::7} # Short version of sha
        with:
          name: slui-pr-${{ github.event.number }}-${{ env.SHA7 }}
          path: ./packages/extension-app/master-build.zip
