name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
# Lint the code
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: ./scripts/prestart.sh
      - run: yarn lint

  # Test the code
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test

  # Create a .zip containing the browser extension
  package-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn package:extension
      - uses: actions/upload-artifact@v1
        with:
          name: slui-${{ github.sha }}
          path: ./packages/extension-app/master-build.zip

  # Create a draft release on each master with the extension
  release:
    runs-on: ubuntu-latest
    needs: package-extension
    steps:
      - name: Download extension zip
        uses: actions/download-artifact@v1
        with:
          name: slui-${{ github.sha }}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: slui-${{ github.sha }}/master-build.zip
          tag_name: draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Upload the webapp to AWS S3
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn build:ui
      - uses: chrislennon/action-aws-cli@v1.1
      - run: aws s3 sync packages/light-apps/build/ s3://slui --acl public-read
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
